language: python
sudo: false
python:
  - "2.7"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry pip install -e . 
script: nosetests test
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
